name: ✨ Feature Request
description: Suggest a new hook or enhancement for the library
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees: ["djkepa"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have checked the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature request is related to React hooks
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New hook
        - Enhancement to existing hook
        - Documentation improvement
        - Developer experience improvement
        - Performance optimization
        - TypeScript improvement
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: hook_name
    attributes:
      label: Hook Name (if new hook)
      description: What would you like to call this hook?
      placeholder: "e.g., useMyAwesomeHook"

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        I'm always frustrated when...
        Currently, there's no way to...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        I would like to see...
        The hook should...
        It could work by...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: How would you like this feature to be used? Provide a code example.
      render: typescript
      placeholder: |
        import { useMyHook } from '@custom-react-hooks/use-my-hook';
        
        function MyComponent() {
          const { value, setValue, reset } = useMyHook(initialValue);
          
          return (
            <div>
              <p>Value: {value}</p>
              <button onClick={() => setValue('new value')}>Set</button>
              <button onClick={reset}>Reset</button>
            </div>
          );
        }

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I considered using...
        Another approach could be...
        Existing libraries like X do this by...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: What requirements should this feature meet?
      options:
        - label: TypeScript support
        - label: SSR (Server-Side Rendering) compatibility
        - label: React 18+ compatibility
        - label: Comprehensive documentation
        - label: Unit tests
        - label: Performance optimized
        - label: Mobile-friendly
        - label: Accessibility considerations

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        1. When building a form with complex validation...
        2. In a data-heavy application where...
        3. For mobile apps that need to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        Related links:
        - Similar implementations: 
        - Inspiration from:
        
        Additional notes:
